import { PetCategory, PetInfo, PetSex } from "./pet-info.component";

export class AvailablePets {
  static availablePets: PetInfo[] = [
    {
      id: 8,
      name: "Chase",
      sex: PetSex.M,
      dob: "2023-09-21",
      category: PetCategory.DOG,
      breed: "Black Labrador Retriever",
      weight: 44,
      imageList: [
        "pets/chase/chase-1.jpeg",
        "pets/chase/chase-2.jpeg",
        "pets/chase/chase-3.jpeg",
        "pets/chase/chase-4.jpeg",
      ],
      color: "Black",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, children.",
      characteristics: "Affectionate, Loyal, Playful, Loves, Smart, Friendly, Gentle",
      description:
        "This sweet pup is about 1 year old, neutered, and weighs 44 pounds. Chase is a lovely, active dog who adores people and enjoys playing with other dogs. He is not timid around new faces and loves to run. He doesn’t guard his food, is very brave, and has a great fondness for sticks and balls. He is also house-trained.",
    },
    {
      id: 9,
      name: "Perla",
      sex: PetSex.F,
      dob: "2022-03-21",
      category: PetCategory.DOG,
      breed: "Black Labrador Retriever",
      weight: 57,
      imageList: [
        "pets/perla/perla-1.jpeg",
        "pets/perla/perla-2.jpeg",
        "pets/perla/perla-3.jpeg",
      ],
      color: "Black",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics: "Affectionate, Gentle, Loves, Loyal, Playful, Quiet, Smart, Friendly",
      description:
        "This adorable 2 to 3 year-old girl is spayed and weighs 57 pounds. She is a mellow, calm, and quiet pup, sweet and loving towards people, and great with both other dogs and cats. Perla has a wonderful nature and is an active dog; she enjoys going for walks and playing with her friends. She is friendly and affectionate, even with new people, and she is fully house-trained.",
    },
    {
      id: 10,
      name: "Luna",
      sex: PetSex.F,
      dob: "2022-09-21",
      category: PetCategory.DOG,
      breed: "Mixed",
      weight: 44,
      imageList: [
        "pets/luna/luna-1.jpeg",
        "pets/luna/luna-2.jpeg",
        "pets/luna/luna-3.jpeg",
        "pets/luna/luna-4.jpeg",
        "pets/luna/luna-5.jpeg",
      ],
      color: "Black",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics: "Curious, Friendly, Gentle, Independent, Loves, Loyal, Playful, Quiet",
      description:
        "This adorable 2-year-old girl is spayed and weighs 20 kg (44 lbs). She is a mellow, sweet pup who loves people and is good with other dogs and kids. Luna's wonderful nature makes her ready for her forever home. As an active dog, she enjoys going for walks and playing with her friends. While Luna may be a little timid at first, she will warm up in a few days and show her sweet personality to everyone around her.",
    },
    {
      id: 11,
      name: "Rich",
      sex: PetSex.M,
      dob: "2022-09-21",
      category: PetCategory.DOG,
      breed: "Mixed",
      weight: 21,
      imageList: [
        "pets/rich/rich-1.jpeg",
        "pets/rich/rich-2.jpeg",
        "pets/rich/rich-3.jpeg",
        "pets/rich/rich-4.jpeg",
      ],
      color: "Brindle, Golden, White / Cream",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics: "Affectionate, Friendly, Brave, Funny, Gentle, Independent, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "A 2-year-old neutered male who weighs 9.5 kg! Rich is a sweet pup who adores his owner. He gets along well with other dogs and cats. An active dog, he loves going for walks and is good on a leash. Rich also has a healthy appetite! Although he needed a few days to adjust to his new home, he quickly settled in.",
    },
  ];

  static adoptedPets = [
    {
      id: 3,
      name: "Toto",
      sex: PetSex.M,
      dob: "2023-07-08",
      category: PetCategory.DOG,
      breed: "",
      weight: 22,
      imageList: [
        "pets/toto/toto1-min.jpeg",
        "pets/toto/toto2-min.jpeg",
        "pets/toto/toto3-min.jpeg",
        "pets/toto/toto4-min.jpeg",
      ],
      color: "Grey",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics: "",
      description:
        "A Loving and Adorable Companion Toto is a charming and affectionate one-year-old pup weighing approximately 22 pounds. <br>He has received all necessary vaccinations, and has been neutered and microchipped. <br>This sweet pup is a delight to be around, boasting a gentle nature that makes him an excellent companion.<br>He is particularly fond of socializing with other dogs and cats, making him an excellent addition to a multi-pet household. <br>Moreover, Toto is potty-trained, making it easy to care for him. <br>Overall, Toto is a loving and loyal companion who would thrive in a loving home with an active family. <br>If you're looking for a friendly and well-mannered pup to join your family, Toto is definitely worth considering.",
    },

    {
      id: 4,
      name: "Pluto",
      sex: PetSex.M,
      dob: "2022-07-08",
      category: PetCategory.DOG,
      breed: "Mixed Breed",
      weight: 27.5,
      imageList: ["pets/pluto/pluto1-min.jpeg", "pets/pluto/pluto2-min.jpg"],
      color: "Black, White",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Friendly, Affectionate, Loyal, Gentle, Playful, Smart, Curious, Funny, Quiet",
      description:
        "A charming 2-year-old pup weighing 27.5 pounds. <br>He is currently on all vaccinations, neutered, and microchipped. <br>Pluto is a social butterfly who adores people and is gentle with other dogs, making him a wonderful addition to any family.",
    },
    {
      id: 5,
      name: "Bell",
      sex: PetSex.M,
      dob: "2019-07-04",
      category: PetCategory.DOG,
      breed: "Golden Retriever",
      weight: 75,
      imageList: [
        "pets/bell/bell1-min.jpeg",
        "pets/bell/bell2-min.jpeg",
        "pets/bell/bell3-min.jpeg",
        "pets/bell/bell4-min.jpeg",
      ],
      color: "Golden",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Affectionate, Brave, Couch, Curious, Gentle, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "A charming 5-year-old neutered male weighing around 75 pounds. <br>This loving and gentle soul is looking for someone to love him for who he is. <br>As a friendly and loyal companion, Bell will be by your side through thick and thin. <br>He's an intelligent, well-behaved, and obedient boy, making him a joy. <br>Bell gets along well with other dogs and would be a fantastic addition to your pack. <br>If you're seeking a mellow, sweet, and loyal companion, look no further than Bell! <br>With his affectionate nature, he's sure to steal your heart and become your best friend.",
    },
    {
      id: 6,
      name: "Lisa",
      sex: PetSex.F,
      dob: "2021-06-29",
      category: PetCategory.DOG,
      breed: "Husky",
      weight: 51,
      imageList: [
        "pets/lisa/lisa1-min.jpeg",
        "pets/lisa/lisa2-min.jpeg",
        "pets/lisa/lisa3-min.jpeg",
      ],
      color: "Black, White",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Friendly, Affectionate, Loyal, Gentle, Playful, Smart, Brave, Curious, Independent, Funny, Athletic, Quiet, Loves Kisses, Loves Kids",
      description:
        "A stunning 3-year-old husky girl weighing 23 kg. She is up-to-date on all vaccinations, spayed, and microchipped. <br>Lisa loves children and is gentle with other dogs, making her a great addition to many families. <br>When she's not playing, she's happy to accompany children who are reading or watching TV, and she even enjoys a relaxing bath.",
    },

    {
      id: 7,
      name: "Suki",
      sex: PetSex.F,
      dob: "2024-05-08",
      category: PetCategory.CAT,
      breed: "Domestic Short Hair",
      weight: 0,
      imageList: [
        "pets/suki/suki1-min.jpeg",
        "pets/suki/suki2-min.jpeg",
        "pets/suki/suki3-min.jpeg",
        "pets/suki/suki4-min.jpeg",
        "pets/suki/suki5-min.jpeg",
        "pets/suki/suki6-min.jpeg",
        "pets/suki/suki7-min.jpeg",
        "pets/suki/suki8-min.jpeg",
      ],
      color: "Grey",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Friendly, Affectionate, Loyal, Gentle, Playful, Smart, Curious, Loves Kisses",
      description:
        "She's already had her first vaccination and is making significant progress. <br>Suki is a friendly and outgoing cat who gets along well with people and other cats. <br>She's also very curious and has already learned to use the litter box.",
    },
  ];
}
