import { PetCategory, PetInfo, PetSex } from "./pet-info.component";

export class AvailablePets {
  static availablePets: PetInfo[] = [
    {
      id: 8,
      name: "Chase",
      sex: PetSex.M,
      dob: "2023-09-21",
      category: PetCategory.DOG,
      breed: "Black Labrador Retriever",
      weight: 44,
      imageList: [
        "pets/chase/chase-1.jpeg",
        "pets/chase/chase-2.jpeg",
        "pets/chase/chase-3.jpeg",
        "pets/chase/chase-4.jpeg",
      ],
      color: "Black",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, children.",
      characteristics:
        "Affectionate, Loyal, Playful, Loves, Smart, Friendly, Gentle",
      description:
        "This sweet pup is about 1 year old, neutered, and weighs 44 pounds. Chase is a lovely, active dog who adores people and enjoys playing with other dogs. He is not timid around new faces and loves to run. He doesn’t guard his food, is very brave, and has a great fondness for sticks and balls. He is also house-trained.",
    },

    {
      id: 10,
      name: "Luna",
      sex: PetSex.F,
      dob: "2022-09-21",
      category: PetCategory.DOG,
      breed: "Mixed",
      weight: 44,
      imageList: [
        "pets/luna/luna-1.jpeg",
        "pets/luna/luna-2.jpeg",
        "pets/luna/luna-3.jpeg",
        "pets/luna/luna-4.jpeg",
        "pets/luna/luna-5.jpeg",
      ],
      color: "Black",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Curious, Friendly, Gentle, Independent, Loves, Loyal, Playful, Quiet",
      description:
        "This adorable 2-year-old girl is spayed and weighs 20 kg (44 lbs). She is a mellow, sweet pup who loves people and is good with other dogs and kids. Luna's wonderful nature makes her ready for her forever home. As an active dog, she enjoys going for walks and playing with her friends. While Luna may be a little timid at first, she will warm up in a few days and show her sweet personality to everyone around her.",
    },

    {
      id: 12,
      name: "Plum",
      sex: PetSex.F,
      dob: "2021-11-03",
      category: PetCategory.DOG,
      breed: "Schnauzer Mixed",
      weight: 26.4,
      imageList: [
        "pets/plum/plum-1.jpeg",
        "pets/plum/plum-2.jpg",
        "pets/plum/plum-3.jpg",
        "pets/plum/plum-4.jpeg",
        "pets/plum/plum-5.jpeg",
      ],
      color: "Tricolor (Brown, Black, & White), Gray / Blue / Silver",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Affectionate, Curious, Friendly, Loves, Loyal, Playful, Quiet, Smart, Gentle",
      description:
        "Plum is an adorable and sweet pup, around 3 years old, weighing 12 kg. This friendly little girl adores people and thrives on the joy of going for walks or runs. she , she quickly warms up and shows her affectionate . she doesn't need any warmup with new people. <br><br>Foster update: Plum is a sweet , friendly girl, good with other dogs and cats. she is a little star in the neighborhood.",
    },
    {
      id: 13,
      name: "Sally",
      sex: PetSex.F,
      dob: "2019-11-03",
      category: PetCategory.DOG,
      breed: "Yellow Labrador Retriever ",
      weight: 77,
      imageList: [
        "pets/sally/sally-1.jpg",
        "pets/sally/sally-2.jpg",
        "pets/sally/sally-3.jpg",
      ],
      color: "Apricot / Beige",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Affectionate, Curious, Friendly, Gentle, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "Sally is five years old and 77 lbs. spayed and her vaccinations are up to date. <br><br>Sally is a beautiful girl with a calm and sweet temperament. She is potty trained and walks well on her leash. <br><br>Sally is a quiet, well-behaved dog who loves petting and cuddling. She and Harry are a couple and are always together, so prefer they be adopted by the same family.",
    },
    {
      id: 14,
      name: "Harry",
      sex: PetSex.M,
      dob: "2019-11-03",
      category: PetCategory.DOG,
      breed: "Yellow Labrador Retriever ",
      weight: 72,
      imageList: [
        "pets/harry/harry-1.jpg",
        "pets/harry/harry-2.jpg",
        "pets/harry/harry-3.jpg",
      ],
      color: "Apricot / Beige",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Curious, Friendly, Funny, Gentle, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "Harry is a five-year-old, 72-pound neutered male with up-to-date vaccinations.<br><br>He’s a handsome boy with an active yet mellow personality. He loves water and is well-behaved, demonstrating excellent obedience. Harry enjoys being petted and is friendly and gentle with both people and other dogs.<br><br>Harry is a couple with Sally, and they are always together. We would prefer that they be adopted by the same family.",
    },
    {
      id: 15,
      name: "Morning",
      sex: PetSex.F,
      dob: "2015-11-03",
      category: PetCategory.DOG,
      breed: " Chow Chow",
      weight: 0,
      imageList: [
        "pets/morning/morning-1.jpg",
        "pets/morning/morning-2.jpg",
        "pets/morning/morning-3.jpg",
        "pets/morning/morning-4.jpg",
        "pets/morning/morning-5.jpg",
      ],
      color: "Golden, Apricot / Beige",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Affectionate, Friendly, Funny, Gentle, Loyal, Playful, Quiet",
      description:
        "Morning is a healthy 9-year-old female dog who is fully house-trained.<br><br>Morning loves spending time outdoors. She adores cats and rabbits, even if they don't reciprocate her affection. While she is friendly with other dogs, she shows little interest in playing with them, often choosing to ignore them instead. Her favorite season is winter, when she can frolic in the snow and enjoy all-you-can-eat ice cream.<br><br>This sweet pup has a cat-like demeanor, spending most of her time napping. She has never chewed on anything other than her food or damaged any furniture. When the weather isn’t great for a walk, she uses a pad to pee at home as needed.<br><br>Morning sheds twice a year, in spring and fall, with each shedding period lasting 1-2 months. She doesn’t shed at all during the other months.",
    },
    {
      id: 16,
      name: "Pepper",
      sex: PetSex.M,
      dob: "2014-11-03",
      category: PetCategory.DOG,
      breed: "Schnauzer",
      weight: 0,
      imageList: [
        "pets/pepper/pepper-1.jpg",
        "pets/pepper/pepper-2.jpg",
        "pets/pepper/pepper-3.jpg",
        "pets/pepper/pepper-4.jpg",
        "pets/pepper/pepper-5.jpg",
        "pets/pepper/pepper-.jpg",
      ],
      color: "Gray / Blue / Silver",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Affectionate, Brave, Friendly, Funny, Gentle, Loves, Loyal, Playful, Quiet",
      description:
        "Pepper is a delightful 10-year-old male dog who is not only healthy but also fully house-trained. He has a warm and loving personality, is incredibly sweet and loyal, and is always eager to snuggle up for cozy cuddles. He is quiet and has a fondness for female dogs of all sizes, from miniature terriers to retrievers, and gets along well with them all. Pepper is the perfect match if you're looking for a gentle and affectionate friend!",
    },
    {
      id: 17,
      name: "Stella",
      sex: PetSex.F,
      dob: "2019-11-03",
      category: PetCategory.DOG,
      breed: "Mixed Breed ",
      weight: 0,
      imageList: [
        "pets/stella/stella-1.jpg",
        "pets/stella/stella-2.jpg",
        "pets/stella/stella-3.jpg",
      ],
      color: "",
      healthStatus: "",
      personality: "",
      houseTrained: false,
      idealFamily: "",
      characteristics:
        "Affectionate, Friendly, Gentle, Loves, Loyal, Playful, Quiet",
      description:
        "Stella is a delightful 5-year-old female dog who brings joy to everyone around her. She is in excellent health, and her vaccinations are up to date. Stella is a gentle, affectionate girl who adores her owner and is known for her unwavering loyalty to her human companions.<br><br>With a warm and loving personality, Stella is lovely and well-mannered. She may need a few days to warm up and be cuddled with new people, but she is friendly to everyone she meets. Stella embodies the spirit of companionship and will bring happiness to any family lucky enough to welcome her into their lives.",
    },
    {
      id: 18,
      name: "Coco",
      sex: PetSex.F,
      dob: "2021-11-03",
      category: PetCategory.DOG,
      breed: "Mixed Breed ",
      weight: 15,
      imageList: [
        "pets/coco/coco-1.jpeg",
        "pets/coco/coco-2.jpeg",
      ],
      color: "",
      healthStatus: "",
      personality: "",
      houseTrained: false,
      idealFamily: "",
      characteristics:
        "Friendly, Gentle, Independent, Loves, Loyal, Playful, Smart, Affectionate, Quiet",
      description:
        "Coco is a 3-year-old female dog weighing 15 pounds. Her calm and gentle demeanor makes her the perfect companion for anyone seeking a loyal pet. Coco loves people and does not suffer from separation anxiety; she can remain alone calmly. She is good with other dogs and has a gentle nature. Additionally, Coco walks nicely on her leash.",
    },
    {
      id: 19,
      name: "Mina",
      sex: PetSex.F,
      dob: "2023-05-03",
      category: PetCategory.DOG,
      breed: "Mixed Breed ",
      weight: 22,
      imageList: [
        "pets/mina/mina-1.jpg",
      ],
      color: "White / Cream",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Affectionate, Friendly, Gentle, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "Mina is a 1.5-year-old female dog who weighs 22 pounds. She is lovely with both people and other dogs, and she loves cuddling and being petted. Although she isn't afraid of new people, she does take a little time to warm up before she's ready for cuddles. Mina does not guard her food and is friendly with cats and kids. She is potty trained and walks well on a leash.",
    },
    {
      id: 20,
      name: "Zena",
      sex: PetSex.F,
      dob: "2022-05-03",
      category: PetCategory.DOG,
      breed: "Mixed Breed ",
      weight: 17,
      imageList: [
        "pets/zena/zena-1.jpeg",
        "pets/zena/zena-2.jpeg",
        "pets/zena/zena-2.jpeg",
      ],
      color: "Apricot / Beige, Golden, Yellow / Tan / Blond / Fawn",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Affectionate, Friendly, Gentle, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "Zena is a 2.5-year-old female dog weighing 17 pounds. She is a well-behaved, quiet pup and isn't a picky eater. Zena gets along well with other dogs and cats, making her a great choice as the only pet or as one of several dogs in the family.",
    },
  ];

  static adoptedPets = [
    {
      id: 3,
      name: "Toto",
      sex: PetSex.M,
      dob: "2023-07-08",
      category: PetCategory.DOG,
      breed: "",
      weight: 22,
      imageList: [
        "pets/toto/toto1-min.jpeg",
        "pets/toto/toto2-min.jpeg",
        "pets/toto/toto3-min.jpeg",
        "pets/toto/toto4-min.jpeg",
      ],
      color: "Grey",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics: "",
      description:
        "A Loving and Adorable Companion Toto is a charming and affectionate one-year-old pup weighing approximately 22 pounds. <br>He has received all necessary vaccinations, and has been neutered and microchipped. <br>This sweet pup is a delight to be around, boasting a gentle nature that makes him an excellent companion.<br>He is particularly fond of socializing with other dogs and cats, making him an excellent addition to a multi-pet household. <br>Moreover, Toto is potty-trained, making it easy to care for him. <br>Overall, Toto is a loving and loyal companion who would thrive in a loving home with an active family. <br>If you're looking for a friendly and well-mannered pup to join your family, Toto is definitely worth considering.",
    },

    {
      id: 4,
      name: "Pluto",
      sex: PetSex.M,
      dob: "2022-07-08",
      category: PetCategory.DOG,
      breed: "Mixed Breed",
      weight: 27.5,
      imageList: ["pets/pluto/pluto1-min.jpeg", "pets/pluto/pluto2-min.jpg"],
      color: "Black, White",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Friendly, Affectionate, Loyal, Gentle, Playful, Smart, Curious, Funny, Quiet",
      description:
        "A charming 2-year-old pup weighing 27.5 pounds. <br>He is currently on all vaccinations, neutered, and microchipped. <br>Pluto is a social butterfly who adores people and is gentle with other dogs, making him a wonderful addition to any family.",
    },
    {
      id: 5,
      name: "Bell",
      sex: PetSex.M,
      dob: "2019-07-04",
      category: PetCategory.DOG,
      breed: "Golden Retriever",
      weight: 75,
      imageList: [
        "pets/bell/bell1-min.jpeg",
        "pets/bell/bell2-min.jpeg",
        "pets/bell/bell3-min.jpeg",
        "pets/bell/bell4-min.jpeg",
      ],
      color: "Golden",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Affectionate, Brave, Couch, Curious, Gentle, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "A charming 5-year-old neutered male weighing around 75 pounds. <br>This loving and gentle soul is looking for someone to love him for who he is. <br>As a friendly and loyal companion, Bell will be by your side through thick and thin. <br>He's an intelligent, well-behaved, and obedient boy, making him a joy. <br>Bell gets along well with other dogs and would be a fantastic addition to your pack. <br>If you're seeking a mellow, sweet, and loyal companion, look no further than Bell! <br>With his affectionate nature, he's sure to steal your heart and become your best friend.",
    },
    {
      id: 6,
      name: "Lisa",
      sex: PetSex.F,
      dob: "2021-06-29",
      category: PetCategory.DOG,
      breed: "Husky",
      weight: 51,
      imageList: [
        "pets/lisa/lisa1-min.jpeg",
        "pets/lisa/lisa2-min.jpeg",
        "pets/lisa/lisa3-min.jpeg",
      ],
      color: "Black, White",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Friendly, Affectionate, Loyal, Gentle, Playful, Smart, Brave, Curious, Independent, Funny, Athletic, Quiet, Loves Kisses, Loves Kids",
      description:
        "A stunning 3-year-old husky girl weighing 23 kg. She is up-to-date on all vaccinations, spayed, and microchipped. <br>Lisa loves children and is gentle with other dogs, making her a great addition to many families. <br>When she's not playing, she's happy to accompany children who are reading or watching TV, and she even enjoys a relaxing bath.",
    },

    {
      id: 7,
      name: "Suki",
      sex: PetSex.F,
      dob: "2024-05-08",
      category: PetCategory.CAT,
      breed: "Domestic Short Hair",
      weight: 0,
      imageList: [
        "pets/suki/suki1-min.jpeg",
        "pets/suki/suki2-min.jpeg",
        "pets/suki/suki3-min.jpeg",
        "pets/suki/suki4-min.jpeg",
        "pets/suki/suki5-min.jpeg",
        "pets/suki/suki6-min.jpeg",
        "pets/suki/suki7-min.jpeg",
        "pets/suki/suki8-min.jpeg",
      ],
      color: "Grey",
      healthStatus: "",
      personality: "",
      houseTrained: true,
      idealFamily: "",
      characteristics:
        "Friendly, Affectionate, Loyal, Gentle, Playful, Smart, Curious, Loves Kisses",
      description:
        "She's already had her first vaccination and is making significant progress. <br>Suki is a friendly and outgoing cat who gets along well with people and other cats. <br>She's also very curious and has already learned to use the litter box.",
    },

    {
      id: 9,
      name: "Perla",
      sex: PetSex.F,
      dob: "2022-03-21",
      category: PetCategory.DOG,
      breed: "Black Labrador Retriever",
      weight: 57,
      imageList: [
        "pets/perla/perla-1.jpeg",
      ],
      color: "Black",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Affectionate, Gentle, Loves, Loyal, Playful, Quiet, Smart, Friendly",
      description:
        "This adorable 2 to 3 year-old girl is spayed and weighs 57 pounds. She is a mellow, calm, and quiet pup, sweet and loving towards people, and great with both other dogs and cats. Perla has a wonderful nature and is an active dog; she enjoys going for walks and playing with her friends. She is friendly and affectionate, even with new people, and she is fully house-trained.",
    },
    {
      id: 11,
      name: "Rich",
      sex: PetSex.M,
      dob: "2022-09-21",
      category: PetCategory.DOG,
      breed: "Mixed",
      weight: 21,
      imageList: [
        "pets/rich/rich-1.jpeg",
      ],
      color: "Brindle, Golden, White / Cream",
      healthStatus: "Vaccinations up to date, spayed / neutered.",
      personality: "",
      houseTrained: true,
      idealFamily: "Other dogs, cats, children.",
      characteristics:
        "Affectionate, Friendly, Brave, Funny, Gentle, Independent, Loves, Loyal, Playful, Quiet, Smart",
      description:
        "A 2-year-old neutered male who weighs 9.5 kg! Rich is a sweet pup who adores his owner. He gets along well with other dogs and cats. An active dog, he loves going for walks and is good on a leash. Rich also has a healthy appetite! Although he needed a few days to adjust to his new home, he quickly settled in.",
    },
  ];
}
