export class BreedList {
  static CatBreedList: string[] = [
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Sphynx",
    "American Wirehair",
    "Balinese",
    "Bengal",
    "Birman",
    "Birmans",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Burmilian",
    "Chartreux",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Donskoy",
    "Egyptian Mau",
    "Finnish Lapphund",
    "Foreign White",
    "German Rex",
    "Havana Brown",
    "Himalayan",
    "Japanese Bobtail",
    "Javanese",
    "Khao Manee",
    "Korat",
    "Kurilian Bobtail",
    "LaPerm",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Mixed",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest Cat",
    "Ocicat",
    "Ojos Azules",
    "Oriental Shorthair",
    "Persian",
    "Peterbald",
    "Pixie Bob",
    "Polish Cat",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Saber",
    "Savannah",
    "Scottish Fold",
    "Siberian",
    "Singapura",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Turkish Angora",
    "Turkish Van",
    "Ukrainian Levkoy",
    "Van (Turkish)",
    "Woolly (Russian)",
    "Other",
  ];

  static DogBreedList: string[] = [
    "Airedale Terrier",
    "American Foxhound",
    "American Staffordshire Terrier",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Basset Hound",
    "Beagle",
    "Belgian Malinois",
    "Bernese Mountain Dog",
    "Bloodhound",
    "Border Collie",
    "Boxer",
    "Brittany Spaniel",
    "Bull Terrier",
    "Cairn Terrier",
    "Chihuahua",
    "Cocker Spaniel",
    "Collie",
    "Corgi (Pembroke and Cardigan)",
    "Dachshund",
    "Doberman Pinscher",
    "English Setter",
    "Golden Retriever",
    "Great Dane",
    "Greyhound",
    "Irish Setter",
    "Jack Russell Terrier",
    "Labrador Retriever",
    "Mastiff",
    "Miniature Schnauzer",
    "Mixed",
    "Old English Sheepdog",
    "Pomeranian",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Scottish Terrier",
    "Sheltie (Shetland Sheepdog)",
    "Shih Tzu",
    "Siberian Husky",
    "Springer Spaniel",
    "Vizsla",
    "Weimaraner",
    "West Highland White Terrier (Westie)",
    "Whippet",
    "Yorkshire Terrier (Yorkie)",
    "Other",
  ];
}
